![banner CSharp - Exce√ß√µes](https://github.com/AnaProgramando/CSharp_Excecoes/blob/09a5f8fc94afc38948c1ab022b4ea6752f608e0b/CSharp_Excecoes.png)
----

<img src="https://img.shields.io/static/v1?label=Status&message=complete&color=32CD32&style=for-the-badge"/>

<p align="center">
 <a href="#-welcome">Welcome</a> | 
 <a href="#-csharp---exce%C3%A7%C3%B5es">Exce√ß√µes</a> | 
 <a href="#-material-base">Material base</a> | 
 <a href="#-primeiros-passos-com-exce%C3%A7%C3%B5es">Primeiros passos com exce√ß√µes</a> | 
 <a href="#-tratamento-de-exce%C3%A7%C3%B5es">Tratamento de exce√ß√µes</a> | 
 <a href="#-argumentexception-paramname-e-nameof">ArgumentException ParamName e nameof</a> | 
 <a href="#-criando-exce%C3%A7%C3%B5es-ricas">Criando exce√ß√µes ricas</a> | 
 <a href="#-stacktrace-e-innerexception">StackTrace e InnerException</a> | 
 <a href="#-finally-e-using">Finally e using</a> | 
 <a href="#-refer%C3%AAncias">Refer√™ncias</a> | 
 <a href="#-d%C3%BAvidas">D√∫vidas</a> | 
 <a href="#%EF%B8%8F-contatos">Contatos</a> | 
 <a href="#%EF%B8%8F-desenvolvedora">Desenvolvedora</a>
</p>

# ü§ó Welcome

Ol√°, seja muito bem vinda(o)! 

Tive a ideia de come√ßar o desafio de #100DaysOfCode, al√©m de compartilhar alguns projetos para quem tem interesse em aprender C#, por isso se trata de algo bem simples para quem gostaria de iniciar na programa√ß√£o ou precisa melhorar as suas habilidades.

<br>

## <img align="center" alt="Ana-Csharp" height="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/csharp/csharp-original.svg"> CSharp - Exce√ß√µes

üìö Aproveite o c√≥digo desse exerc√≠cio

üë©‚Äçüíª Refa√ßa do seu jeito

üòâ Se tiver qualquer d√∫vida, me contate

<br>

## üìö Material base

Para seguir os passos abaixo e trabalhar com exce√ß√µes baixe o projeto que trata de heran√ßas e interfaces [clicando aqui](https://github.com/AnaProgramando/CSharp_Heranca-e-interface).

<br>

## üë£ Primeiros passos com exce√ß√µes 

- Abra o arquivo Program.cs 

- Crie o m√©todo dividir:
```
public static int Dividir(int numero, int divisor)
{
    return numero / divisor;
}
```

- Para visualizar a CallStack, crie os m√©todos Metodo() e TestaDivisao():

###### üí¨ CallStack: Se trata de uma cadeia de caracteres que cont√©m informa√ß√µes do rastreamento de pilha.

```
static void Metodo()
{
    TestaDivisao(0);
}
static void TestaDivisao(int divisor)
{
    Dividir(10, divisor);
}
```

- No m√©todo Main, fa√ßa uma chamada ao Metodo():

```
static void Main(string[] args)
{
    Metodo();
    Console.ReadLine();
}
```

- Execute a aplica√ß√£o

###### üí¨ Ser√° poss√≠vel ver que houve uma exce√ß√£o n√£o tratada, pois a CLR (Common Language Runtime) n√£o encontrou um manipulador dessa exce√ß√£o no c√≥digo, por isso o Visual Studio exibiu as informa√ß√µes da exce√ß√£o e execu√ß√£o do programa.

###### üí¨ CLR: O .NET fornece um ambiente de tempo de execu√ß√£o, chamado de Common Language Runtime, que executa o c√≥digo e fornece servi√ßos que facilitam o processo de desenvolvimento. 

- Para tratar a exce√ß√£o, adicione um bloco try/catch para o tipo DivideByZeroException no m√©todo Main:

```
static void Main(string[] args)
{
    try
    {
        Metodo();
    }
    catch (DivideByZeroException)
    {
        Console.WriteLine("Exce√ß√£o tratada.");
    }
    Console.ReadLine();
}
```

###### üí¨ Ao executar a aplica√ß√£o, ir√° imprimir a exce√ß√£o tratada e continuar executando, aguardando o m√©todo Console.ReadLine() retornar. Quando uma exce√ß√£o √© lan√ßada, o CLR procura a instru√ß√£o catch que trata essa exce√ß√£o. Se o m√©todo em execu√ß√£o no momento n√£o contiver um bloco catch, o CLR procurar√° no m√©todo que chamou o m√©todo atual e assim por diante para cima na pilha de chamadas. Se nenhum bloco catch for encontrado, o CLR exibir√° uma mensagem de exce√ß√£o sem tratamento para o usu√°rio e interromper√° a execu√ß√£o do programa.

###### üí¨ Try: O bloco try cont√©m o c√≥digo protegido que pode causar a exce√ß√£o, e ele √© executado at√© que uma exce√ß√£o seja lan√ßada ou ocorra a conclus√£o com √™xito.

###### üí¨ Catch: O bloco catch especifica os manipuladores para diferentes exce√ß√µes. Usar argumentos catch √© uma maneira de filtrar as exce√ß√µes que deseja manipular. Na ocorr√™ncia de uma exce√ß√£o, a m√°quina virtual visita, de cima para baixo, os blocos catch definidos.

###### üí¨  No C# os erros N√ÉO s√£o os n√∫meros que estamos acostumados a ver e que muitas vezes precisamos buscar o significado, nele os erros s√£o objetos.

- Nomeie a refer√™ncia para a exce√ß√£o do tipo DivideByZeroException:

```
catch (DivideByZeroException excecao)
```

###### üí¨ catch(DivideByZeroException) - Informa que n√£o √© poss√≠vel fazer uma divis√£o por 0.

- Utilize as duas propriedades da exce√ß√£o Message e StackTrace para o rastro da pilha entre lan√ßamento de exce√ß√£o e o tratamento no bloco catch:

###### üí¨ Message: A mensagem de erro que explica o motivo da exce√ß√£o ou de uma cadeia de caracteres vazia (""). O texto da propriedade Message deve descrever completamente o erro e, quando poss√≠vel, tamb√©m explicar como corrig√≠-lo. Eles tamb√©m podem exibir a mensagem para os usu√°rios finais, de modo que voc√™ deve verificar se ela est√° gramaticalmente correta, se cada frase da mensagem termina com ponto, sem o uso de interroga√ß√£o ou exclama√ß√£o.

###### üí¨ StackTrace: A propriedade StackTrace retorna os quadros da pilha de chamadas que se originam no local onde a exce√ß√£o foi gerada, mostrando uma cadeia de caracteres que descreve os quadros imediatos da pilha de chamadas. A pilha de execu√ß√£o mant√©m o controle de todos os m√©todos que est√£o em execu√ß√£o em um determinado instante. Um rastreamento das chamadas de m√©todo √© chamado de rastreamento de pilha, e a listagem de rastreamento de pilha fornece uma maneira de seguir a pilha de chamadas para o n√∫mero de linha no m√©todo em que ocorre a exce√ß√£o.

```
catch (DivideByZeroException excecao)
{
    Console.WriteLine(excecao.Message);
    Console.WriteLine(excecao.StackTrace);
}
```

###### üí¨ Executando a StackTrace temos a mensagem de tentativa de divis√£o por zero, e em seguida uma descri√ß√£o da trilha seguida pela chamada dos m√©todos, primeiro Dividir() e, em seguida o TestaDivisao().

- Para testar outro tipo de exce√ß√£o, tente acessar um membro de uma refer√™ncia nula no m√©todo Dividir:

```
static int Dividir(int numero, int divisor)
{
    ContaCorrente conta = null;
    Console.WriteLine(conta.Saldo);
    return numero / divisor;
}
```

###### üí¨ Executando a aplica√ß√£o √© poss√≠vel ver que a exce√ß√£o do tipo NullReferenceException foi lan√ßada e n√£o houve tratamento, pois s√≥ temos blocos try e catch para o tipo DivideByZeroException.

- Adicione um tratamento para esta exce√ß√£o no m√©todo Metodo:

```
static void Metodo()
{
    try
    {
        TestaDivisao(0);
    }
    catch (NullReferenceException excecao)
    {
        Console.WriteLine(excecao.Message);
        Console.WriteLine(excecao.StackTrace);
    }
}
```

###### üí¨ Executando a aplica√ß√£o podemos observar que o processo n√£o √© encerrado abruptamente e houve uma altera√ß√£o nos dados apresentados na menssagem do StackTrace, pois a exce√ß√£o foi tratada em Metodo e n√£o no Main.

<br>

## üìö Tratamento de exce√ß√µes

- Mantenha o bloco try/catch apenas no m√©todo Main e remova os outros.

- Crie um bloco try com v√°rios catch‚Äôs para testar, adicione para estes tipos de exce√ß√µes no Main:

```
static void Main(string[] args)
{
    try
    {
        Metodo();
    }
    catch (DivideByZeroException excecao)
    {
        Console.WriteLine(excecao.Message);
        Console.WriteLine(excecao.StackTrace);
    }
    catch (NullReferenceException excecao)
    {
        Console.WriteLine(excecao.Message);
        Console.WriteLine(excecao.StackTrace);
    }
    Console.ReadLine();
}
```

- Execute a aplica√ß√£o com a linha "Console.WriteLine(conta.Saldo)"" do m√©todo Dividir, depois execute comentando esse trecho, note que as exce√ß√µes s√£o tratadas pelo m√©todo Main.

- Simplifique os blocos catch e trate apenas o tipo Exception:

###### üí¨ Todas as exce√ß√µes no .NET derivam do tipo Exception, √© nela onde as propriedades Message e StackTrace s√£o definidas.

```
static void Main(string[] args)
{
    try
    {
        Metodo();
    }
    catch (Exception excecao)
    {
        Console.WriteLine(excecao.Message);
        Console.WriteLine(excecao.StackTrace);
    }
    Console.ReadLine();
}
```

- Execute com e sem coment√°rio no trecho "Console.WriteLine(conta.Saldo)" verificando os resultados.

- Crie um tratamento especial para a exce√ß√£o do tipo DivideByZeroException, adicionando o bloco catch ap√≥s o catch(Exception excecao):

```
static void Main(string[] args)
{
    try
    {
        Metodo();
    }
    catch (Exception excecao)
    {
        Console.WriteLine(excecao.Message);
        Console.WriteLine(excecao.StackTrace);
    }
    catch (DivideByZeroException excecao)
    {
        Console.WriteLine("N√£o √© poss√≠vel divis√£o por 0!");
    }
    Console.ReadLine();
}
```

###### üí¨ Como o CLR verifica os blocos catch de cima para baixo, colocando na ordem Exception -> DivideByZeroException, os tratamentos de tipos mais derivados nunca ser√£o executados. 

- Inverta a ordem dos catchs, definindo primeiro os tipos de exce√ß√£o mais derivados, e depois de tipos menos derivados:

```
static void Main(string[] args)
{
    try
    {
        Metodo();
    }
    catch (DivideByZeroException excecao)
    {
        Console.WriteLine("N√£o √© poss√≠vel divis√£o por 0!");
    }
    catch (Exception excecao)
    {
        Console.WriteLine(excecao.Message);
        Console.WriteLine(excecao.StackTrace);
    }
    Console.ReadLine();
}
```

- Adicione um bloco try/catch no m√©todo Dividir para realizar uma a√ß√£o antes de propagar a exce√ß√£o para o m√©todo seguinte:

```
static int Dividir(int numero, int divisor)
{
    try
    {
        return numero / divisor;
    }
    catch (Exception)
    {
        Console.WriteLine("Exce√ß√£o com numero=" + numero + " e divisor=" + divisor);
    }
}
```

###### üí¨ Como a CLR entende que foi manipulada a exce√ß√£o no m√©todo Dividir, logo se trata de um caminho sem a instru√ß√£o return, o que √© incorreto.

- Use a palavra reservada throw no bloco catch para propagar a exce√ß√£o para o pr√≥ximo m√©todo da callstack:

###### üí¨ Throw (lan√ßar): √â poss√≠vel tratar uma exce√ß√£o simplesmente criando-se uma notifica√ß√£o da sua ocorr√™ncia, e continuar propagando-a pela pilha de chamadas. Quando usamos a palavra reservada "throw" o compilador deixa de identificar o erro no c√≥digo, posto que √© um controle de fluxo, ele indica o encerramento do m√©todo, ent√£o qualquer c√≥digo que estiver abaixo dele n√£o ser√° executado.

```
static int Dividir(int numero, int divisor)
{
    try
    {
        return numero / divisor;
    }
    catch (Exception)
    {
        Console.WriteLine("Exce√ß√£o com numero=" + numero + " e divisor=" + divisor);
        throw;
    }
}
```

###### üí¨ Quando temos um throw vazio dentro de um bloco catch, a m√°quina virtual passa o objeto de exce√ß√£o para o pr√≥ximo m√©todo na pilha de chamadas, assim sucessivamente at√© encontrar um bloco catch que possa pegar a exce√ß√£o.

- A conven√ß√£o √© utilizar o nome "e" ou "ex" no nome exception para as vari√°veis de exce√ß√£o capturadas nos blocos catch, ent√£o altere o "exception".

<br>

## üìö ArgumentException ParamName e nameof

- Como os setters das propriedades Numero e Agencia n√£o s√£o necess√°rios, altere a defini√ß√£o destas propriedades para:

```
public int Agencia { get; }
public int Numero { get; }
```

- A verifica√ß√£o de Numero e Agencia devem estar no construtor. Adicione o c√≥digo para verificar se os valores das vari√°veis int agencia e int numero s√£o maiores que 0 e, caso contr√°rio, lan√ßar uma exce√ß√£o.

- O .NET possui uma classe para representar uma exce√ß√£o de argumento inv√°lido, a ArgumentException:

###### üí¨ ArgumentException: A exce√ß√£o que √© gerada quando um dos argumentos fornecidos para um m√©todo n√£o √© v√°lido.

```
public ContaCorrente(int agencia, int numero)
{
    if (agencia <= 0)
    {
        throw new ArgumentException();
    }

    if(numero <= 0)
    {
        throw new ArgumentException();
    }

    Agencia = agencia;
    Numero = numero;

    TotalDeContasCriadas++;
    TaxaOperacao = 30 / TotalDeContasCriadas;
}
```

- A classe ArgumentException possui um construtor mais espec√≠fico. Use-o para oferecer mais informa√ß√µes na mensagem (propriedade Message) da exce√ß√£o e o nome do par√¢metro (propriedade ParamName) com valor inv√°lido:

###### üí¨ ParamName: Obt√©m o nome do par√¢metro que causa uma exce√ß√£o.

```
if (agencia <= 0)
{
    throw new ArgumentException("O argumento agencia deve ser maior que 0.", "agencia");
}

if(numero <= 0)
{
    throw new ArgumentException("O argumento numero deve ser maior que 0.", "numero");
}
```

- Se mudar o nome do argumento, o compilador n√£o ir√° for√ßar a atualiza√ß√£o do conte√∫do das strings usadas para representar o nome dos argumentos. Para isto, use o operador nameof():

###### üí¨ nameof: Uma express√£o nameof produz o nome de uma vari√°vel, tipo ou membro como a constante de cadeia de caracteres.

```
if (agencia <= 0)
{
    throw new ArgumentException("O argumento agencia deve ser maior que 0.", nameof(agencia));
}

if(numero <= 0)
{
    throw new ArgumentException("O argumento numero deve ser maior que 0.", nameof(numero));
}
```

- Teste a exce√ß√£o ArgumentException em seu programa, com um try/catch para esta exce√ß√£o, exibindo a propriedade ParamName para verificar o argumento inv√°lido e a Message:

```
try
{
    ContaCorrente conta = new ContaCorrente(0, 0);
}
catch (ArgumentException e)
{
    Console.WriteLine(e.Message);
    Console.WriteLine(e.ParamName);
}
```

<br>

## üìö Criando exce√ß√µes ricas

- Certifique-se de que o construtor da classe ContaCorrente n√£o est√° com erro na l√≥gica para o c√°lculo da TaxaOperacao, calculando-a antes de incrementar a propriedade TotalDeContasCriadas:

```
public ContaCorrente(int agencia, int numero)
{
    // c√≥digo omitido
    TotalDeContasCriadas++;
    TaxaOperacao = 30 / TotalDeContasCriadas;
}
```

- Na raiz do projeto, crie a classe SaldoInsuficienteException, seguindo a conven√ß√£o de nomes de exce√ß√µes no .NET.

- Toda exce√ß√£o deve derivar do tipo Exception, por isso altere a classe rec√©m-criada para respeitar esta restri√ß√£o da linguagem e do .NET:

```
public class SaldoInsuficienteException : Exception
{
}
```

- Crie os construtores sem argumentos, e um com uma string mensagem de argumento:

```
public class SaldoInsuficienteException : Exception
{
    public SaldoInsuficienteException()
    {
    }

    public SaldoInsuficienteException(string mensagem)
        : base(mensagem)
    {
    }
}
```

- Guarde o valor de saldo e o valor do saque para guardar mais informa√ß√µes sobre o estado da aplica√ß√£o no momento de lan√ßamento desta exce√ß√£o. Crie estas propriedades somente-leitura e o construtor que os popula:

```
public double Saldo { get; }
public double ValorSaque { get; }
public SaldoInsuficienteException(double saldo, double valorSaque)
    : this("Tentativa de saque de " + valorSaque + " com saldo de " + saldo)
{
    Saldo = saldo;
    ValorSaque = valorSaque;
}
```

- Voltando √† classe ContaCorrente, use a classe de exce√ß√£o no m√©todo Sacar, para isso altere o tipo de retorno deste m√©todo para void e remova o return true. e return false.:

```
public void Sacar(double valor)
{
    if (_saldo < valor)
    {

    }
    _saldo -= valor;
}
```

- Para sinalizar o estado inv√°lido da aplica√ß√£o, lance uma exce√ß√£o do tipo SaldoInsuficienteException:

```
public void Sacar(double valor)
{
    if (_saldo < valor)
    {
        throw new SaldoInsuficienteException(_saldo, valor);
    }
    _saldo -= valor;
}
```

- Adicione esta verifica√ß√£o para o caso do valor de saque ser negativo:

```
public void Sacar(double valor)
{
    if (valor < 0)
    {
        throw new ArgumentException("Valor de saque n√£o pode ser negativo", nameof(valor));
    }
    if (_saldo < valor)
    {
        throw new SaldoInsuficienteException(_saldo, valor);
    }
    _saldo -= valor;
}
```

- Use o m√©todo Sacar no m√©todo Transferir:

```
public void Transferir(double valor, ContaCorrente contaDestino)
{
    if (valor < 0)
    {
        throw new ArgumentException("Valor inv√°lido para a transfer√™ncia.", nameof(valor));
    }

    Sacar(valor);

    contaDestino.Depositar(valor);
}
```

<br>

## üìö StackTrace e InnerException

- Crie a propriedade ContadorSaquesNaoPermitidos:

```
public int ContadorSaquesNaoPermitidos { get; private set; }
```

- Incremente este contador no m√©todo sacar:

```
if (_saldo < valor)
{
    ContadorSaquesNaoPermitidos++;
    throw new SaldoInsuficienteException(Saldo, valor);
}
```

- Fa√ßa o mesmo com as transfer√™ncias, crie a propriedade ContadorTransferenciasNaoPermitidas:

```
public int ContadorTransferenciasNaoPermitidas { get; private set; }
```

- Para incrementar este contador, use o bloco try/catch no m√©todo Transferir:

```
try
{
    Sacar(valor);
}
catch(SaldoInsuficienteException ex)
{
    ContadorTransferenciasNaoPermitidas++;
    throw;
}
```

- No catch do m√©todo Transferir foi lan√ßada a exce√ß√£o com a instru√ß√£o throw, sem uma express√£o de exce√ß√£o, e gra√ßas a esta sintaxe, a CLR n√£o altera a propriedade StackTrace da exce√ß√£o e mant√©m a informa√ß√£o intacta.

- √â poss√≠vel encapsular uma cadeia de exce√ß√µes por meio da InnerException, crie a OperacaoFinanceiraException para isto:

```
public class OperacaoFinanceiraException : Exception
{
    public OperacaoFinanceiraException()
    {

    }

    public OperacaoFinanceiraException(string mensagem)
        : base(mensagem)
    {

    }

    public OperacaoFinanceiraException(string mensagem, Exception excecaoInterna)
        : base(mensagem, excecaoInterna)
    {

    }
}
```

- Foram criados 3 construtores de exce√ß√£o, conforme as conven√ß√µes da Microsoft: construtor sem argumentos, construtor com mensagem e construtor com mensagem e InnerException.

- Agora √© poss√≠vel usar a exce√ß√£o:

```
throw new OperacaoFinanceiraException("Opera√ß√£o n√£o realizada.", ex);
```

- No programa, escreva o c√≥digo para testar esta exce√ß√£o e verificar que, apesar do StackTrace da exce√ß√£o lan√ßada nascer no m√©todo Transferir, d√° para verificar a InnerException e saber de onde a exce√ß√£o original partiu:

```
try
{
    ContaCorrente conta1 = new ContaCorrente(1234, 123456);
    ContaCorrente conta2 = new ContaCorrente(4321, 654321);

    // conta1.Transferir(10000, conta2);
    conta1.Sacar(10000);
}
catch (OperacaoFinanceiraException e)
{
    Console.WriteLine(e.Message);
    Console.WriteLine(e.StackTrace);

    Console.WriteLine("Informa√ß√µes da INNER EXCEPTION (exce√ß√£o interna):");

    Console.WriteLine(e.InnerException.Message);
    Console.WriteLine(e.InnerException.StackTrace);
}
```

###### üí¨ inner exceptions: Se trata de um objeto que descreve o erro que causou a exce√ß√£o atual. A propriedade InnerException retorna o mesmo valor passado para o construtor Exception(String, Exception), ou null, se o valor de exce√ß√£o interno n√£o foi fornecido para o construtor.

<br>

## üìö Finally e using

###### üí¨ finally: Quando ocorre uma exce√ß√£o, a execu√ß√£o √© interrompida e o controle √© dado ao manipulador de exce√ß√£o apropriado. Geralmente, isso significa que linhas de c√≥digo que voc√™ espera que sejam executadas s√£o ignoradas. A limpeza de alguns recursos, assim como o fechamento de um arquivo, precisar√° ser feita mesmo se uma exce√ß√£o for gerada. Para fazer isso, voc√™ pode usar um bloco finally. Um bloco finally sempre √© executado, independentemente de uma exce√ß√£o ser ou n√£o gerada. Usando um bloco finally, voc√™ pode limpar todos os recursos alocados em um bloco try e pode executar c√≥digo mesmo se uma exce√ß√£o ocorrer no bloco try. 

###### üí¨ using: A instru√ß√£o using √© encerrada ao final do bloco de instru√ß√µes "using" ou quando a execu√ß√£o sai do bloco indiretamente, por exemplo - quando uma exce√ß√£o for lan√ßada. Al√©m disso, a instru√ß√£o "using" permite especificar v√°rios recursos em uma √∫nica instru√ß√£o.

- Crie a classe LeitorDeArquivo com o c√≥digo abaixo. Certifique-se de adicionar no cabe√ßalho do arquivo desta classe a diretiva using System.IO; pois ser√£o usadas classes deste namespace:

```
public class LeitorDeArquivo
{
    public string Arquivo { get; }

    public LeitorDeArquivo(string arquivo)
    {
        Arquivo = arquivo;

        // throw new FileNotFoundException();
        Console.WriteLine("Abrindo arquivo: " + arquivo);
    }

    public string LerProximaLinha()
    {
        Console.WriteLine("Lendo linha. . .");

        // throw new IOException();
        return "Linha do arquivo";
    }

    public void Fechar()
    {
        Console.WriteLine("Fechando arquivo.");
    }
}
```

- Escreva o c√≥digo de teste para esta classe:

```
private static void CarregarContas()
{
    LeitorDeArquivo leitor =  new LeitorDeArquivo("contas.txt");

    leitor.LerProximaLinha();
    leitor.LerProximaLinha();
    leitor.LerProximaLinha();

    leitor.Fechar();
}
```

- Executando o m√©todo CarregarContas(), voc√™ encontrar√° a sa√≠da:

> Abrindo arquivo: contas.txt
> Lendo linha. . .
> Lendo linha. . .
> Lendo linha. . .
> Fechando arquivo.

- Para simular problemas em ler o arquivo, lance uma exce√ß√£o do tipo IOException em LerProximaLinha:

```
public string LerProximaLinha()
{
    Console.WriteLine("Lendo linha. . .");

    throw new IOException();
    return "Linha do arquivo";
}
```

- Com esta altera√ß√£o feita, ser√° necess√°rio tratar a exce√ß√£o em CarregarContas, pois √© fundamental chamar o m√©todo Fechar:

```
LeitorDeArquivo leitor =  new LeitorDeArquivo("contas.txt");
try
{
    leitor.LerProximaLinha();
    leitor.LerProximaLinha();
    leitor.LerProximaLinha();
    leitor.Fechar();
}
catch(IOException e)
{
    leitor.Fechar();
    Console.WriteLine("Exce√ß√£o do tipo IOException capturada e tratada.");
}
```

- Podemos evitar esta duplica√ß√£o do c√≥digo leitor.Fechar(), onde temos um c√≥digo que deve ser executado ao fim do try e ao fim do catch, quando houver uma exce√ß√£o, podemos usar o finally:

```
LeitorDeArquivo leitor =  new LeitorDeArquivo("contas.txt");
try
{
    leitor.LerProximaLinha();
    leitor.LerProximaLinha();
    leitor.LerProximaLinha();
}
catch(IOException e)
{
    Console.WriteLine("Exce√ß√£o do tipo IOException capturada e tratada.");
}
finally
{
    leitor.Fechar();
}
```

- Existem outras exce√ß√µes em potencial na leitura de arquivos, como quando o arquivo n√£o √© encontrado. Vamos simular isto atrav√©s da altera√ß√£o no construtor da classe LeitorDeArquivo:

```
public LeitorDeArquivo(string arquivo)
{
    Arquivo = arquivo;

    throw new FileNotFoundException();
    Console.WriteLine("Abrindo arquivo: " + arquivo);
}
```

- Agora ser√° necess√°rio mover a instancia√ß√£o desta classe para dentro do bloco try:

```
LeitorDeArquivo leitor = null;
try
{
    leitor = new LeitorDeArquivo("contas.txt");
    leitor.LerProximaLinha();
    leitor.LerProximaLinha();
    leitor.LerProximaLinha();
}
catch(IOException e)
{
    Console.WriteLine("Exce√ß√£o do tipo IOException capturada e tratada.");
}
finally
{
    leitor.Fechar();
}
```

- Executar este c√≥digo pode gerar problemas, pois a tentativa de atribui√ß√£o na vari√°vel leitor ir√° gerar uma exce√ß√£o e, no bloco finally uma uma refer√™ncia nula. Verifique:

```
finally
{
    if(leitor != null)
    {
        leitor.Fechar();
    }
}
```

- Como a √∫nica fun√ß√£o de nosso try/catch/finally √© ter certeza de que o m√©todo Fechar do recurso foi invocado, √© poss√≠vel trocar ele pelo bloco using:

```
using(LeitorDeArquivo leitor = new LeitorDeArquivo("contas.txt"))
{
    leitor.LerProximaLinha();
    leitor.LerProximaLinha();
    leitor.LerProximaLinha();
}
```

- O bloco using √© um a√ß√∫car sint√°tico para o c√≥digo escrito no try/finally, mas o bloco using n√£o conhece o m√©todo Fechar, apenas o m√©todo Dispose da interface IDisposable. Altere a classe LeitorDeArquivo e implemente a interface:

###### üí¨ dispose: A implementa√ß√£o do m√©todo Dispose destina-se principalmente √† libera√ß√£o de recursos n√£o gerenciados. O Framework chama o m√©todo Dispose dos objetos especificados na instru√ß√£o "using" quando o bloco √© encerrado.

###### üí¨ IDisposable: Os objetos especificados no bloco using devem implementar a interface IDisposable, e ele fornece um mecanismo para liberar recursos n√£o gerenciados.

```
public class LeitorDeArquivo : IDisposable
{
    public string Arquivo { get; }

    public LeitorDeArquivo(string arquivo)
    {
        Arquivo = arquivo;

        // throw new FileNotFoundException();
        Console.WriteLine("Abrindo arquivo: " + arquivo);
    }

    public string LerProximaLinha()
    {
        Console.WriteLine("Lendo linha. . .");

        // throw new IOException();
        return "Linha do arquivo";
    }

    public void Fechar()
    {
        Console.WriteLine("Fechando arquivo.");
    }
}
```

- Troque o nome do m√©todo Fechar para Dispose:

```
public void Dispose()
{
    Console.WriteLine("Fechando arquivo.");
}
```

<br>

## ‚úç Refer√™ncias

Existem diversos exerc√≠cios, artigos e v√≠deos sobre C# por a√≠, por isso recomendo que voc√™s deem uma olhada nos cursos incr√≠veis da Alura e no MSDN (Microsoft Developer Network), pois ambos tem muitos conte√∫dos e explica√ß√µes para ajudarem a nos desenvolvermos e sanar as nossas d√∫vidas.

üìò [Alura](https://www.alura.com.br/)
<br>
A maior plataforma brasileira de cursos de tecnologia.

üìó [MSDN](https://docs.microsoft.com/pt-br/?redirectedfrom=MSDN)
<br>
Central de documenta√ß√£o e aprendizado da Microsoft para desenvolvedores

üìí [Documenta√ß√£o do C#](https://docs.microsoft.com/pt-br/dotnet/csharp/)
<br>
Saiba como escrever qualquer aplicativo usando a linguagem de programa√ß√£o C# na plataforma .NET.

<br>

## ‚ùì D√∫vidas

Qualquer d√∫vida, interaja aqui:
  * Fa√ßa perguntas
  * D√™ sugest√µes de melhoria para o projeto
  * Compartilhe suas ideias
  * E interaja sobre o assunto

üòâLembre-se de que esta √© uma comunidade que constru√≠mos juntos üí™.

<br>

## ‚úâÔ∏è Contatos

Se precisar de ajuda, entre em contato comigo üòâ

[<img align="left" alt="Gmail" width="80px" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white"/>](mailto:anabe.valentim@gmail.com)
[<img align="left" alt="LinkedIn" width="100px" src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white"/>](https://www.linkedin.com/in/ana-beatriz-valentim)
[<img align="left" alt="Beacons" width="80px" src="https://github.com/AnaProgramando/AnaProgramando/blob/31ac40741768033915a37ec0f949984bf6aad2d1/beacons_logo.png"/>](https://beacons.page/anaprogramando)

<br>
<br>

## üôã‚Äç‚ôÄÔ∏è Desenvolvedora

<div>
  <img align="left" alt="Ana Valentim" width="100px" src="https://avatars.githubusercontent.com/u/31097110?v=4"/>
</div>

<br>
‚úèÔ∏è Feito com ‚ù§Ô∏è e C# por <a href="https://github.com/AnaProgramando">Ana Valentim</a>.

üíô Se voc√™ gostou desse projeto, d√™ uma ‚≠ê e compartilhe!

<br><br>
[<img align="right" alt="Voltar ao topo" width="100px" src="https://img.shields.io/static/v1?label&message=Voltar+ao+topo&color=blueviolet&style=flat&logo"/>](https://github.com/AnaProgramando/CSharp_Excecoes/blob/main/README.md#)


<div>
  <img align="center" alt="Pixel-Art" width="1000px" src="https://github.com/AnaProgramando/CSharp_Declaracao-Caracteres-e-Textos/blob/d77aca3327c866f2508eb049cb245586d8dd0fd3/suicide%20squad.gif"/>
</div>
